server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost/tp2_car_db
    username: postgres
    password: password_dev
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

app:
  secret: tp2Secret
  token-validity-in-seconds: 3600